workflows:
  flutter_build_and_distribute:
    name: Flutter Build and Distribute
    max_build_duration: 60
    triggering:
       events:
          - push
          - pull_request
    scripts:
      - name: Build for iOS
        script: |
          flutter build ios
          
      - name: Install Firebase CLI
        script: |
          npm install -g firebase-tools

      - name: Upload APK to Firebase
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:594502835954:ios:a6ae6d7481b994d5103a6b \
            --groups testers \
            --token 1//0g09ZpnM-sjpCCgYIARAAGBASNwF-L9IrqOSf0ENiMXiq6GbPbQ5nWAcWARRcBPE6-zIUIfbIIO9rAYQWnqqSr95L8fLyaZV7dHY

    # 构建产物
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/Runner.ipa
